
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/dell/Documents/winlibs-mingw/mingw64/share/cmake-4.0/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The target system is: Emscripten - 1 - x86
      The host system is: Windows - 6.2.9200 - AMD64
...
